name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  linttest:
    strategy:
        matrix:
          go: [1.13, 1.14, 1.15]
          grafana: [6.7.1, 6.6.2, 6.5.3, 6.4.5]

    env:
      GRAFANA_INTEGRATION: 1

    services:
      # Label used to access the service container
      grafana:
        # Docker Hub image
        image: "grafana/grafana:${{ matrix.grafana }}"
        ports:
          - 3000:3000
        env:
          GF_AUTH_ANONYMOUS_ENABLED: true
      chromedp:
        image: "chromedp/headless-shell"
        ports:
          - 9222:9222
        options: >-
          --shm-size 2G

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Run linters
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.37

    - name: Test
      run: go test -v ./...
